.TH "src/core/Button.h" 3 "Version 3.5" "EncButton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core/Button.h \- \fBButton\fP class for handling button presses and debouncing\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include 'VirtButton\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBButton\fP"
.br
.RI "Represents a button that extends the \fBVirtButton\fP class\&. "
.ti -1c
.RI "class \fBButtonT< PIN >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBButton\fP class for handling button presses and debouncing\&. 


.PP
Definition in file \fBButton\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EncButton from the source code\&.
