.TH "src/core Directory Reference" 3 "Version 3.5" "EncButton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBButton\&.h\fP"
.br
.RI "\fBButton\fP class for handling button presses and debouncing\&. "
.ti -1c
.RI "file \fBEncButton\&.h\fP"
.br
.RI "\fBEncButton\fP class for handling rotary encoder with button\&. "
.ti -1c
.RI "file \fBEncoder\&.h\fP"
.br
.RI "\fBEncoder\fP class for handling rotary encoder\&. "
.ti -1c
.RI "file \fButils\&.cpp\fP"
.br
.ti -1c
.RI "file \fButils\&.h\fP"
.br
.RI "Utility functions for handling pins and flags\&. "
.ti -1c
.RI "file \fBVirtButton\&.h\fP"
.br
.RI "\fBVirtButton\fP class for handling virtual buttons\&. "
.ti -1c
.RI "file \fBVirtEncButton\&.h\fP"
.br
.RI "Virtual encoder button class\&. "
.ti -1c
.RI "file \fBVirtEncoder\&.h\fP"
.br
.RI "Virtual encoder class\&. "
.in -1c
