.TH "src/EncButton.h" 3 "Version 3.5" "EncButton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/EncButton.h
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include 'core/VirtButton\&.h'\fP
.br
\fC#include 'core/VirtEncoder\&.h'\fP
.br
\fC#include 'core/VirtEncButton\&.h'\fP
.br
\fC#include 'core/Button\&.h'\fP
.br
\fC#include 'core/Encoder\&.h'\fP
.br
\fC#include 'core/EncButton\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for EncButton from the source code\&.
