.TH "src/core/Encoder.h" 3 "Version 3.5" "EncButton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core/Encoder.h \- \fBEncoder\fP class for handling rotary encoder\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include 'VirtEncoder\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEncoder\fP"
.br
.RI "The \fBEncoder\fP class represents an encoder device\&. "
.ti -1c
.RI "class \fBEncoderT< ENCA, ENCB >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBEncoder\fP class for handling rotary encoder\&. 


.PP
Definition in file \fBEncoder\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EncButton from the source code\&.
