.TH "todo" 3 "Version 3.5" "EncButton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.PP

.IP "\fBMember \fBVirtEncButton::action\fP ()\fP" 1c
todo in binary switch case block e_state + b_state and EB_HOLD + EB_TURN verification if ((state & EB_HOLD) && (state & EB_TURN_R)) return EB_TURN_HOLD_R; 
.PP

